name: kolacheck
description: Early tea leaf disease detection for Sri Lankan smallholders.
publish_to: none
version: 0.1.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0
  image_picker: ^1.1.2
  image: ^4.2.0
  http: ^1.2.2
flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/labels.txt
